

* TODO протестировать tea_picture
  - Note taken on [2013-11-30 Сб. 00:34] \\
    Не должно давать постить левым пользователям

    Должно давать удалять только свои картинки, либо любые,
    если ты - владелец чая

* TODO протестировать tea_link
  - Note taken on [2013-11-30 Сб. 00:35] \\
    аналогично tea_picture

* TODO коменты для чаев
* TODO интеграционные тесты
  - Note taken on [2013-11-30 Сб. 00:40] \\
    Особо не упарывать, главное - осилить, сделать по минимуму
* TODO логин через социальные сети
* TODO Не удалять чай, если есть другие пользователи
  - Note taken on [2013-11-30 Сб. 00:36] \\
    Если чай находится в списках у других пользователей, то
    при удалении чая он просто отвязывается от текущего
    пользователя и переназначается другому, рандомному.
* TODO В чае показывать оси
  - Note taken on [2013-11-30 Сб. 00:43] \\
    На странице с чаем показывать внизу оси

    на каждой оси слева непосредственно слабые чаи,
    справа - сильные. Это пока будет замена полноценным
    осям
* TODO Сделать оси
  - Note taken on [2013-11-30 Сб. 00:41] \\
    Для этого придется решить задачку раскладывания графа
    на плоскости
