nix:
  packages:
    - pkg-config
    - libffi
    - llvm_8

resolver: lts-14.6

packages:
- .

extra-deps:
  - accelerate-1.2.0.1
  - accelerate-llvm-native-1.2.0.1
  - accelerate-llvm-1.2.0.1
  - accelerate-arithmetic-1.0.0.1
