#!/bin/bash
dev=$1
echo ":::::creating file system"
umount /dev/${dev}1
if ! mkdosfs -F 32 /dev/${dev}1;then
	echo "::::::ошибко"
	exit 1
fi
echo ":::::mounting"
mountpoint /media/${dev}1&&umount /media/${dev}1
[ -e /media/${dev}1 ]&&rm -rf /media/${dev}1
mkdir /media/${dev}1
if ! mount /dev/${dev}1 /media/${dev}1;then
	echo "::::::не смонтировалося"
	exit 2
fi
echo ":::::copying files to flash drive"
if ! cp -r flashroot/* /media/${dev}1;then
	echo "::::::копирование не прошло"
	exit 3
fi
echo ":::::umounting"
umount /dev/${dev}1
rm -rf /media/${dev}1
echo ":::::puting loader"
if ! syslinux /dev/${dev}1;then
	echo ":::::::загрузчик не залился"
	exit 4
fi
echo ":::::puting mbr"
dd if=/usr/share/syslinux/mbr.bin of=/dev/${dev}
echo ":::::making it bootable"
parted /dev/${dev} set 1 boot on
echo ":::::end"
