######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 26 22:35:01 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Ngram.h
SOURCES += Ngram.cpp \
    Main.cpp
